---
- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: restart pve-firewall
  ansible.builtin.service:
    name: pve-firewall
    state: restarted

- name: Restart PVE Proxy
  ansible.builtin.systemd:
    name: pveproxy
    state: restarted